<a href="https://colab.research.google.com/github/PedroConst/EQE-358-Metodos-Numericos/blob/main/Gabaritos/Lista_Extra_1_Gabarito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista 01: Exercícios Extras (Gabarito)

Os exercícios abaixo são sugeridos para que você pratique a escrita de expressões matemáticas em Python. A lista é recomendada aos que estão dando os primeiros passos na jornada da programação.




---
**Exercício 1:** Calcule a área do triângulo de base 5 e altura 7.


---

$A= (b \times h)/2$



In [ ]:
5*7/2

17.5

---
**Exercício 2:** Calcule a área superficial e o volume de um cilindro com raio $R=4$ e altura $h = 10$.


---
$A = 2\pi R(h + R)$ <br>
$V = \pi R^2 h$

In [ ]:
import math

2*math.pi*4*(10+4)

351.85837720205683

In [ ]:
math.pi*4**2*10

502.6548245743669

---
**Exercício 3:** Calcule o valor de $7!$


---

In [ ]:
import math

math.factorial(7)

5040

---
**Exercício 4:** Calcule o valor de $\cosh (x)$ para $x=2$, usando a definição com exponenciais e usando a função `cosh` do módulo `math`.


---

$\cosh(x)=(e^{x}+e^{-x})/2$

In [ ]:
import math

(math.exp(2)+math.exp(-2))/2

3.7621956910836314

In [ ]:
math.cosh(2)

3.7621956910836314

---
**Exercício 5:** Verifique que $\sin^2(x) + \cos^2(x)=1$ para os valores de $x=\pi, \frac{\pi}{2}, \frac{\pi}{4}, \frac{\pi}{6}$


---

In [ ]:
import math

print(math.sin(math.pi)**2 + math.cos(math.pi)**2)
print(math.sin(math.pi/2)**2 + math.cos(math.pi/2)**2)
print(math.sin(math.pi/4)**2 + math.cos(math.pi/4)**2)
print(math.sin(math.pi/6)**2 + math.cos(math.pi/6)**2)

1.0
1.0
1.0
1.0


---
**Exercício 6:** Calcule o valor de $\cos 36°$


---



In [ ]:
import math

math.cos(36*math.pi/180)

0.8090169943749475

In [ ]:
math.cos(36)    # ERRADO! Atenção: o argumento da função precisa estar em radianos.

-0.12796368962740468



---
**Exercício 1:** Seja $x=5$ e $y=8$. Escreva uma linha de código que realize cada uma das operações a seguir:

*   $u=2x+3y$
*   $v=5xy$
*   $w=7x/4y$
*   $z=\sin(x)$
*   $r=8\cos(y)$
*   $s=5\sin^2(xy)$
*   $p=9x^y$

---




In [ ]:
import math

x = 5
y = 8

In [ ]:
u = 2*x+3*y
print(u)

34


In [ ]:
v = 5*x*y
print(v)

200


In [ ]:
w = 7*x/(4*y)
print(w)

1.09375


In [ ]:
z = math.sin(x)
print(z)

-0.9589242746631385


In [ ]:
r = 8*math.cos(y)
print(r)

-1.1640002704689083


In [ ]:
s = 5*math.sin(x*y)**2
print(s)

2.775968109597619


In [ ]:
p = 9*x**y
print(p)

3515625




---
**Exercício 2:** Calcule as mesmas operações do exercício anterior (elemento a elemento) para os vetores $x=[1,3,5,7,9,11]$ e $y=[2,4,6,8,10,12]$ .


---




In [ ]:
import numpy as np

x = np.array([1,3,5,7,9,11])
y = np.array([2,4,6,8,10,12])

In [ ]:
u = 2*x+3*y
print(u)
v = 5*x*y
print(v)
w = 7*x/(4*y)
print(w)
z = np.sin(x)
print(z)
r = 8*np.cos(y)
print(r)
s = 5*np.sin(x*y)**2
print(s)
p = 9*x**y
print(p)

[ 8 18 28 38 48 58]
[ 10  60 150 280 450 660]
[0.875      1.3125     1.45833333 1.53125    1.575      1.60416667]
[ 0.84147098  0.14112001 -0.95892427  0.6569866   0.41211849 -0.99999021]
[-3.32917469 -5.22914897  7.68136229 -1.16400027 -6.71257223  6.75083167]
[4.13410905 1.43955248 4.88103245 1.36007724 3.99615017 0.01408934]
[             9            729         140625       51883209
    31381059609 28245855390489]




---
**Exercício 3:** Mostre todas as variáveis armazenadas no Jupyter Notebook após os exercícios anteriores. Em seguida, limpe todas as variáveis.


---




In [ ]:
%whos

Variable   Type       Data/Info
-------------------------------
math       module     <module 'math' (built-in)>
np         module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
p          ndarray    6: 6 elems, type `int64`, 48 bytes
r          ndarray    6: 6 elems, type `float64`, 48 bytes
s          ndarray    6: 6 elems, type `float64`, 48 bytes
u          ndarray    6: 6 elems, type `int64`, 48 bytes
v          ndarray    6: 6 elems, type `int64`, 48 bytes
w          ndarray    6: 6 elems, type `float64`, 48 bytes
x          ndarray    6: 6 elems, type `int64`, 48 bytes
y          ndarray    6: 6 elems, type `int64`, 48 bytes
z          ndarray    6: 6 elems, type `float64`, 48 bytes


In [ ]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y




---
**Exercício 4:** Gere um array de tamanho $50$ com pontos igualmente espaçados entre $-5$ e $5$.


---




In [ ]:
import numpy as np

np.linspace(-5,5,50)

array([-5.        , -4.79591837, -4.59183673, -4.3877551 , -4.18367347,
       -3.97959184, -3.7755102 , -3.57142857, -3.36734694, -3.16326531,
       -2.95918367, -2.75510204, -2.55102041, -2.34693878, -2.14285714,
       -1.93877551, -1.73469388, -1.53061224, -1.32653061, -1.12244898,
       -0.91836735, -0.71428571, -0.51020408, -0.30612245, -0.10204082,
        0.10204082,  0.30612245,  0.51020408,  0.71428571,  0.91836735,
        1.12244898,  1.32653061,  1.53061224,  1.73469388,  1.93877551,
        2.14285714,  2.34693878,  2.55102041,  2.75510204,  2.95918367,
        3.16326531,  3.36734694,  3.57142857,  3.7755102 ,  3.97959184,
        4.18367347,  4.3877551 ,  4.59183673,  4.79591837,  5.        ])



---
**Exercício 5:** Crie uma matriz de zeros $4 \times 4$ e modifique os elementos diagonais para transformar em uma matriz identidade.


---




In [ ]:
import numpy as np

I = np.zeros((4,4))

I[0,0]=1
I[1,1]=1
I[2,2]=1
I[3,3]=1

print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]




---
**Exercício 6:** Implemente uma função que receba a temperatura em Celsius como entrada e calcule a temperatura em Farenheit como saída. Imprima o resultado na tela como:
```python
A temperatura X graus Celsius equivale a Y graus Farenheit.
```

---




In [ ]:
def CparaF(T):

    out = 9*T/5+32
    print(f"A temperatura {T} graus Celsius equivale a {out} graus Farenheit")
    return

CparaF(0)

A temperatura 0 graus Celsius equivale a 32.0 graus Farenheit




---
**Exercício 7:** Escreva uma função chamada `xadrez` onde a saída seja uma matriz $n \times n$ com a seguinte forma:

$A_{n,n} = \begin{pmatrix}
1 & 0 & 1 &\cdots & 0 & 1\\
0 & 1 & 0 &\cdots & 1 & 0\\
\vdots  & \vdots  & \vdots &\ddots & \vdots &\vdots \\
0 & 1 & 0 &\cdots & 1 & 0\\
1 & 0 & 1 &\cdots & 0 & 1\\
\end{pmatrix}$


---




In [ ]:
import numpy as np

def xadrez(n):

    out = np.zeros((n,n)) # criar uma matriz zeros n x n

    # A matriz tem valor 1 quando ambos índices são pares ou ímpares
    out[0:n:2,0:n:2]=1    # 0:n:2 são os números pares
    out[1:n:2,1:n:2]=1    # 1:n:2 são os números ímpares

    return out

xadrez(5)

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])



---
**Exercício 8:** Implemente uma função que calcule a área e o volume de um cilindro dado o seu raio `r` e altura `h`.

---




In [ ]:
import numpy as np

def cilindro(r,h):

    area = 2*np.pi*r*(r+h)
    volume = np.pi*r**2*h

    return [area, volume]

cilindro(1,5)

[37.69911184307752, 15.707963267948966]