<a href="https://colab.research.google.com/github/PedroConst/EQE-358-Metodos-Numericos/blob/main/Aulas/Aula_4_Algebra_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Álgebra Linear em Python

## Definir Matriz

In [ ]:
import numpy as np

A = np.array([[1, 0], [0, 1]])
B = np.array([[4, 1], [2, 2]])

## Multiplicação de Matrizes

In [ ]:
M = A*B     #Produto elemento a elemento! Cuidado!!
print(M)

[[4 0]
 [0 2]]


In [ ]:
M = np.dot(A,B)
print(M)

[[4 1]
 [2 2]]


In [ ]:
M = np.matmul(A, B)
print(M)

[[4 1]
 [2 2]]


In [ ]:
M = A @ B
print(M)

[[4 1]
 [2 2]]


## Determinantes

In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

D = np.linalg.det(A)
print(D)

-2.0000000000000004


In [ ]:
from numpy.linalg import det

D = det(A)
print(D)

-2.0000000000000004


## Matriz Inversa

In [ ]:
import numpy as np
from numpy.linalg import inv

#A = np.array([[1., 2.], [3., 4.]])
A = np.array([[1., -2.,0], [0., 1.,2],[2., 2.,0]])
Ainv = inv(A)

print(Ainv)

[[ 0.33333333  0.          0.33333333]
 [-0.33333333 -0.          0.16666667]
 [ 0.16666667  0.5        -0.08333333]]


In [ ]:
AandB = np.array([[[1., 2.], [3., 4.]], [[1, 3], [3, 5]]])
inv(AandB)

array([[[-2.  ,  1.  ],
        [ 1.5 , -0.5 ]],

       [[-1.25,  0.75],
        [ 0.75, -0.25]]])

## Autovalores e Autovetores

In [ ]:
import numpy as np
from numpy.linalg import eig

In [ ]:
A = np.array([[0, 2],
              [2, 3]])
w,v=eig(A)

print('Autovalores:')
print(w)
print('Autovetores:')
print(v)

Autovalores:
[-1.  4.]
Autovetores:
[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


In [ ]:
a = np.array([[2, 2, 4],
              [1, 3, 5],
              [2, 3, 4]])
w,v=eig(a)

print('Autovalores:')
print(w)
print('Autovetores:')
print(v)

Autovalores:
[ 8.80916362  0.92620912 -0.73537273]
Autovetores:
[[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
